//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudioQualitySpec) DeepCopyInto(out *AudioQualitySpec) {
	*out = *in
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreferAdditional != nil {
		in, out := &in.PreferAdditional, &out.PreferAdditional
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tiers != nil {
		in, out := &in.Tiers, &out.Tiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreferredFormats != nil {
		in, out := &in.PreferredFormats, &out.PreferredFormats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudioQualitySpec.
func (in *AudioQualitySpec) DeepCopy() *AudioQualitySpec {
	if in == nil {
		return nil
	}
	out := new(AudioQualitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationSpec) DeepCopyInto(out *AuthenticationSpec) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationSpec.
func (in *AuthenticationSpec) DeepCopy() *AuthenticationSpec {
	if in == nil {
		return nil
	}
	out := new(AuthenticationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrConfig) DeepCopyInto(out *BazarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrConfig.
func (in *BazarrConfig) DeepCopy() *BazarrConfig {
	if in == nil {
		return nil
	}
	out := new(BazarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BazarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrConfigList) DeepCopyInto(out *BazarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BazarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrConfigList.
func (in *BazarrConfigList) DeepCopy() *BazarrConfigList {
	if in == nil {
		return nil
	}
	out := new(BazarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BazarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrConfigSpec) DeepCopyInto(out *BazarrConfigSpec) {
	*out = *in
	in.Sonarr.DeepCopyInto(&out.Sonarr)
	in.Radarr.DeepCopyInto(&out.Radarr)
	if in.LanguageProfiles != nil {
		in, out := &in.LanguageProfiles, &out.LanguageProfiles
		*out = make([]BazarrLanguageProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]BazarrProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(AuthenticationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Reconciliation != nil {
		in, out := &in.Reconciliation, &out.Reconciliation
		*out = new(ReconciliationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrConfigSpec.
func (in *BazarrConfigSpec) DeepCopy() *BazarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BazarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrConfigStatus) DeepCopyInto(out *BazarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcile != nil {
		in, out := &in.LastReconcile, &out.LastReconcile
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrConfigStatus.
func (in *BazarrConfigStatus) DeepCopy() *BazarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(BazarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrConnectionSpec) DeepCopyInto(out *BazarrConnectionSpec) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrConnectionSpec.
func (in *BazarrConnectionSpec) DeepCopy() *BazarrConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(BazarrConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrLanguage) DeepCopyInto(out *BazarrLanguage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrLanguage.
func (in *BazarrLanguage) DeepCopy() *BazarrLanguage {
	if in == nil {
		return nil
	}
	out := new(BazarrLanguage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrLanguageProfile) DeepCopyInto(out *BazarrLanguageProfile) {
	*out = *in
	if in.Languages != nil {
		in, out := &in.Languages, &out.Languages
		*out = make([]BazarrLanguage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrLanguageProfile.
func (in *BazarrLanguageProfile) DeepCopy() *BazarrLanguageProfile {
	if in == nil {
		return nil
	}
	out := new(BazarrLanguageProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrProvider) DeepCopyInto(out *BazarrProvider) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrProvider.
func (in *BazarrProvider) DeepCopy() *BazarrProvider {
	if in == nil {
		return nil
	}
	out := new(BazarrProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSpec) DeepCopyInto(out *ConnectionSpec) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSpec.
func (in *ConnectionSpec) DeepCopy() *ConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsSecretRef) DeepCopyInto(out *CredentialsSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsSecretRef.
func (in *CredentialsSecretRef) DeepCopy() *CredentialsSecretRef {
	if in == nil {
		return nil
	}
	out := new(CredentialsSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomFormatSpec) DeepCopyInto(out *CustomFormatSpec) {
	*out = *in
	if in.IncludeWhenRenaming != nil {
		in, out := &in.IncludeWhenRenaming, &out.IncludeWhenRenaming
		*out = new(bool)
		**out = **in
	}
	if in.Specifications != nil {
		in, out := &in.Specifications, &out.Specifications
		*out = make([]CustomFormatSpecificationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomFormatSpec.
func (in *CustomFormatSpec) DeepCopy() *CustomFormatSpec {
	if in == nil {
		return nil
	}
	out := new(CustomFormatSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomFormatSpecificationSpec) DeepCopyInto(out *CustomFormatSpecificationSpec) {
	*out = *in
	if in.Negate != nil {
		in, out := &in.Negate, &out.Negate
		*out = new(bool)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomFormatSpecificationSpec.
func (in *CustomFormatSpecificationSpec) DeepCopy() *CustomFormatSpecificationSpec {
	if in == nil {
		return nil
	}
	out := new(CustomFormatSpecificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DelayProfileSpec) DeepCopyInto(out *DelayProfileSpec) {
	*out = *in
	if in.EnableUsenet != nil {
		in, out := &in.EnableUsenet, &out.EnableUsenet
		*out = new(bool)
		**out = **in
	}
	if in.EnableTorrent != nil {
		in, out := &in.EnableTorrent, &out.EnableTorrent
		*out = new(bool)
		**out = **in
	}
	if in.BypassIfHighestQuality != nil {
		in, out := &in.BypassIfHighestQuality, &out.BypassIfHighestQuality
		*out = new(bool)
		**out = **in
	}
	if in.BypassIfAboveCustomFormatScore != nil {
		in, out := &in.BypassIfAboveCustomFormatScore, &out.BypassIfAboveCustomFormatScore
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelayProfileSpec.
func (in *DelayProfileSpec) DeepCopy() *DelayProfileSpec {
	if in == nil {
		return nil
	}
	out := new(DelayProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirectIndexer) DeepCopyInto(out *DirectIndexer) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirectIndexer.
func (in *DirectIndexer) DeepCopy() *DirectIndexer {
	if in == nil {
		return nil
	}
	out := new(DirectIndexer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadClientSpec) DeepCopyInto(out *DownloadClientSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(CredentialsSecretRef)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadClientSpec.
func (in *DownloadClientSpec) DeepCopy() *DownloadClientSpec {
	if in == nil {
		return nil
	}
	out := new(DownloadClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadStackConfig) DeepCopyInto(out *DownloadStackConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadStackConfig.
func (in *DownloadStackConfig) DeepCopy() *DownloadStackConfig {
	if in == nil {
		return nil
	}
	out := new(DownloadStackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DownloadStackConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadStackConfigList) DeepCopyInto(out *DownloadStackConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DownloadStackConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadStackConfigList.
func (in *DownloadStackConfigList) DeepCopy() *DownloadStackConfigList {
	if in == nil {
		return nil
	}
	out := new(DownloadStackConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DownloadStackConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadStackConfigSpec) DeepCopyInto(out *DownloadStackConfigSpec) {
	*out = *in
	out.DeploymentRef = in.DeploymentRef
	in.Gluetun.DeepCopyInto(&out.Gluetun)
	in.Transmission.DeepCopyInto(&out.Transmission)
	if in.Reconciliation != nil {
		in, out := &in.Reconciliation, &out.Reconciliation
		*out = new(ReconciliationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadStackConfigSpec.
func (in *DownloadStackConfigSpec) DeepCopy() *DownloadStackConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DownloadStackConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadStackConfigStatus) DeepCopyInto(out *DownloadStackConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcile != nil {
		in, out := &in.LastReconcile, &out.LastReconcile
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadStackConfigStatus.
func (in *DownloadStackConfigStatus) DeepCopy() *DownloadStackConfigStatus {
	if in == nil {
		return nil
	}
	out := new(DownloadStackConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GluetunDNSSpec) DeepCopyInto(out *GluetunDNSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GluetunDNSSpec.
func (in *GluetunDNSSpec) DeepCopy() *GluetunDNSSpec {
	if in == nil {
		return nil
	}
	out := new(GluetunDNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GluetunFirewallSpec) DeepCopyInto(out *GluetunFirewallSpec) {
	*out = *in
	if in.VPNInputPorts != nil {
		in, out := &in.VPNInputPorts, &out.VPNInputPorts
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.InputPorts != nil {
		in, out := &in.InputPorts, &out.InputPorts
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.OutboundSubnets != nil {
		in, out := &in.OutboundSubnets, &out.OutboundSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GluetunFirewallSpec.
func (in *GluetunFirewallSpec) DeepCopy() *GluetunFirewallSpec {
	if in == nil {
		return nil
	}
	out := new(GluetunFirewallSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GluetunIPv6Spec) DeepCopyInto(out *GluetunIPv6Spec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GluetunIPv6Spec.
func (in *GluetunIPv6Spec) DeepCopy() *GluetunIPv6Spec {
	if in == nil {
		return nil
	}
	out := new(GluetunIPv6Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GluetunKillSwitchSpec) DeepCopyInto(out *GluetunKillSwitchSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GluetunKillSwitchSpec.
func (in *GluetunKillSwitchSpec) DeepCopy() *GluetunKillSwitchSpec {
	if in == nil {
		return nil
	}
	out := new(GluetunKillSwitchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GluetunLoggingSpec) DeepCopyInto(out *GluetunLoggingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GluetunLoggingSpec.
func (in *GluetunLoggingSpec) DeepCopy() *GluetunLoggingSpec {
	if in == nil {
		return nil
	}
	out := new(GluetunLoggingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GluetunProviderSpec) DeepCopyInto(out *GluetunProviderSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(CredentialsSecretRef)
		**out = **in
	}
	if in.PrivateKeySecretRef != nil {
		in, out := &in.PrivateKeySecretRef, &out.PrivateKeySecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GluetunProviderSpec.
func (in *GluetunProviderSpec) DeepCopy() *GluetunProviderSpec {
	if in == nil {
		return nil
	}
	out := new(GluetunProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GluetunServerSpec) DeepCopyInto(out *GluetunServerSpec) {
	*out = *in
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Countries != nil {
		in, out := &in.Countries, &out.Countries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Cities != nil {
		in, out := &in.Cities, &out.Cities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GluetunServerSpec.
func (in *GluetunServerSpec) DeepCopy() *GluetunServerSpec {
	if in == nil {
		return nil
	}
	out := new(GluetunServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GluetunSpec) DeepCopyInto(out *GluetunSpec) {
	*out = *in
	in.Provider.DeepCopyInto(&out.Provider)
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(GluetunServerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Firewall != nil {
		in, out := &in.Firewall, &out.Firewall
		*out = new(GluetunFirewallSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.KillSwitch != nil {
		in, out := &in.KillSwitch, &out.KillSwitch
		*out = new(GluetunKillSwitchSpec)
		**out = **in
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(GluetunDNSSpec)
		**out = **in
	}
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(GluetunIPv6Spec)
		**out = **in
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(GluetunLoggingSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GluetunSpec.
func (in *GluetunSpec) DeepCopy() *GluetunSpec {
	if in == nil {
		return nil
	}
	out := new(GluetunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthIssueStatus) DeepCopyInto(out *HealthIssueStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthIssueStatus.
func (in *HealthIssueStatus) DeepCopy() *HealthIssueStatus {
	if in == nil {
		return nil
	}
	out := new(HealthIssueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthStatus) DeepCopyInto(out *HealthStatus) {
	*out = *in
	if in.LastCheck != nil {
		in, out := &in.LastCheck, &out.LastCheck
		*out = (*in).DeepCopy()
	}
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = make([]HealthIssueStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthStatus.
func (in *HealthStatus) DeepCopy() *HealthStatus {
	if in == nil {
		return nil
	}
	out := new(HealthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportListSpec) DeepCopyInto(out *ImportListSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnableAuto != nil {
		in, out := &in.EnableAuto, &out.EnableAuto
		*out = new(bool)
		**out = **in
	}
	if in.SearchOnAdd != nil {
		in, out := &in.SearchOnAdd, &out.SearchOnAdd
		*out = new(bool)
		**out = **in
	}
	if in.SeasonFolder != nil {
		in, out := &in.SeasonFolder, &out.SeasonFolder
		*out = new(bool)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SettingsSecretRef != nil {
		in, out := &in.SettingsSecretRef, &out.SettingsSecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportListSpec.
func (in *ImportListSpec) DeepCopy() *ImportListSpec {
	if in == nil {
		return nil
	}
	out := new(ImportListSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexerProxy) DeepCopyInto(out *IndexerProxy) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(CredentialsSecretRef)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexerProxy.
func (in *IndexerProxy) DeepCopy() *IndexerProxy {
	if in == nil {
		return nil
	}
	out := new(IndexerProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexersSpec) DeepCopyInto(out *IndexersSpec) {
	*out = *in
	if in.ProwlarrRef != nil {
		in, out := &in.ProwlarrRef, &out.ProwlarrRef
		*out = new(ProwlarrRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Direct != nil {
		in, out := &in.Direct, &out.Direct
		*out = make([]DirectIndexer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexersSpec.
func (in *IndexersSpec) DeepCopy() *IndexersSpec {
	if in == nil {
		return nil
	}
	out := new(IndexersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrConfig) DeepCopyInto(out *LidarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrConfig.
func (in *LidarrConfig) DeepCopy() *LidarrConfig {
	if in == nil {
		return nil
	}
	out := new(LidarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LidarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrConfigList) DeepCopyInto(out *LidarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LidarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrConfigList.
func (in *LidarrConfigList) DeepCopy() *LidarrConfigList {
	if in == nil {
		return nil
	}
	out := new(LidarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LidarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrConfigSpec) DeepCopyInto(out *LidarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Quality != nil {
		in, out := &in.Quality, &out.Quality
		*out = new(AudioQualitySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(MetadataProfileSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DownloadClients != nil {
		in, out := &in.DownloadClients, &out.DownloadClients
		*out = make([]DownloadClientSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RemotePathMappings != nil {
		in, out := &in.RemotePathMappings, &out.RemotePathMappings
		*out = make([]RemotePathMappingSpec, len(*in))
		copy(*out, *in)
	}
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = new(IndexersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Naming != nil {
		in, out := &in.Naming, &out.Naming
		*out = new(LidarrNamingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RootFolders != nil {
		in, out := &in.RootFolders, &out.RootFolders
		*out = make([]LidarrRootFolder, len(*in))
		copy(*out, *in)
	}
	if in.ImportLists != nil {
		in, out := &in.ImportLists, &out.ImportLists
		*out = make([]ImportListSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MediaManagement != nil {
		in, out := &in.MediaManagement, &out.MediaManagement
		*out = new(MediaManagementSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(AuthenticationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]NotificationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomFormats != nil {
		in, out := &in.CustomFormats, &out.CustomFormats
		*out = make([]CustomFormatSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DelayProfiles != nil {
		in, out := &in.DelayProfiles, &out.DelayProfiles
		*out = make([]DelayProfileSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reconciliation != nil {
		in, out := &in.Reconciliation, &out.Reconciliation
		*out = new(ReconciliationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrConfigSpec.
func (in *LidarrConfigSpec) DeepCopy() *LidarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(LidarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrConfigStatus) DeepCopyInto(out *LidarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcile != nil {
		in, out := &in.LastReconcile, &out.LastReconcile
		*out = (*in).DeepCopy()
	}
	in.ManagedResources.DeepCopyInto(&out.ManagedResources)
	if in.ProwlarrRegistration != nil {
		in, out := &in.ProwlarrRegistration, &out.ProwlarrRegistration
		*out = new(ProwlarrRegistration)
		(*in).DeepCopyInto(*out)
	}
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(HealthStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrConfigStatus.
func (in *LidarrConfigStatus) DeepCopy() *LidarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(LidarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrNamingSpec) DeepCopyInto(out *LidarrNamingSpec) {
	*out = *in
	in.NamingSpec.DeepCopyInto(&out.NamingSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrNamingSpec.
func (in *LidarrNamingSpec) DeepCopy() *LidarrNamingSpec {
	if in == nil {
		return nil
	}
	out := new(LidarrNamingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrRootFolder) DeepCopyInto(out *LidarrRootFolder) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrRootFolder.
func (in *LidarrRootFolder) DeepCopy() *LidarrRootFolder {
	if in == nil {
		return nil
	}
	out := new(LidarrRootFolder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResources) DeepCopyInto(out *ManagedResources) {
	*out = *in
	if in.QualityProfileID != nil {
		in, out := &in.QualityProfileID, &out.QualityProfileID
		*out = new(int)
		**out = **in
	}
	if in.CustomFormatIDs != nil {
		in, out := &in.CustomFormatIDs, &out.CustomFormatIDs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.DownloadClientIDs != nil {
		in, out := &in.DownloadClientIDs, &out.DownloadClientIDs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.IndexerIDs != nil {
		in, out := &in.IndexerIDs, &out.IndexerIDs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.RootFolderIDs != nil {
		in, out := &in.RootFolderIDs, &out.RootFolderIDs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.RemotePathMappingIDs != nil {
		in, out := &in.RemotePathMappingIDs, &out.RemotePathMappingIDs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.NotificationIDs != nil {
		in, out := &in.NotificationIDs, &out.NotificationIDs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResources.
func (in *ManagedResources) DeepCopy() *ManagedResources {
	if in == nil {
		return nil
	}
	out := new(ManagedResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaManagementSpec) DeepCopyInto(out *MediaManagementSpec) {
	*out = *in
	if in.RecycleBinCleanupDays != nil {
		in, out := &in.RecycleBinCleanupDays, &out.RecycleBinCleanupDays
		*out = new(int)
		**out = **in
	}
	if in.SetPermissions != nil {
		in, out := &in.SetPermissions, &out.SetPermissions
		*out = new(bool)
		**out = **in
	}
	if in.DeleteEmptyFolders != nil {
		in, out := &in.DeleteEmptyFolders, &out.DeleteEmptyFolders
		*out = new(bool)
		**out = **in
	}
	if in.CreateEmptyFolders != nil {
		in, out := &in.CreateEmptyFolders, &out.CreateEmptyFolders
		*out = new(bool)
		**out = **in
	}
	if in.UseHardlinks != nil {
		in, out := &in.UseHardlinks, &out.UseHardlinks
		*out = new(bool)
		**out = **in
	}
	if in.WatchLibraryForChanges != nil {
		in, out := &in.WatchLibraryForChanges, &out.WatchLibraryForChanges
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaManagementSpec.
func (in *MediaManagementSpec) DeepCopy() *MediaManagementSpec {
	if in == nil {
		return nil
	}
	out := new(MediaManagementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataProfileSpec) DeepCopyInto(out *MetadataProfileSpec) {
	*out = *in
	if in.PrimaryTypes != nil {
		in, out := &in.PrimaryTypes, &out.PrimaryTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecondaryTypes != nil {
		in, out := &in.SecondaryTypes, &out.SecondaryTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReleaseStatuses != nil {
		in, out := &in.ReleaseStatuses, &out.ReleaseStatuses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataProfileSpec.
func (in *MetadataProfileSpec) DeepCopy() *MetadataProfileSpec {
	if in == nil {
		return nil
	}
	out := new(MetadataProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamingSpec) DeepCopyInto(out *NamingSpec) {
	*out = *in
	if in.RenameMedia != nil {
		in, out := &in.RenameMedia, &out.RenameMedia
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamingSpec.
func (in *NamingSpec) DeepCopy() *NamingSpec {
	if in == nil {
		return nil
	}
	out := new(NamingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationSpec) DeepCopyInto(out *NotificationSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.OnGrab != nil {
		in, out := &in.OnGrab, &out.OnGrab
		*out = new(bool)
		**out = **in
	}
	if in.OnDownload != nil {
		in, out := &in.OnDownload, &out.OnDownload
		*out = new(bool)
		**out = **in
	}
	if in.OnUpgrade != nil {
		in, out := &in.OnUpgrade, &out.OnUpgrade
		*out = new(bool)
		**out = **in
	}
	if in.OnRename != nil {
		in, out := &in.OnRename, &out.OnRename
		*out = new(bool)
		**out = **in
	}
	if in.OnHealthIssue != nil {
		in, out := &in.OnHealthIssue, &out.OnHealthIssue
		*out = new(bool)
		**out = **in
	}
	if in.OnHealthRestored != nil {
		in, out := &in.OnHealthRestored, &out.OnHealthRestored
		*out = new(bool)
		**out = **in
	}
	if in.OnApplicationUpdate != nil {
		in, out := &in.OnApplicationUpdate, &out.OnApplicationUpdate
		*out = new(bool)
		**out = **in
	}
	if in.OnManualInteractionRequired != nil {
		in, out := &in.OnManualInteractionRequired, &out.OnManualInteractionRequired
		*out = new(bool)
		**out = **in
	}
	if in.IncludeHealthWarnings != nil {
		in, out := &in.IncludeHealthWarnings, &out.IncludeHealthWarnings
		*out = new(bool)
		**out = **in
	}
	if in.OnMovieAdded != nil {
		in, out := &in.OnMovieAdded, &out.OnMovieAdded
		*out = new(bool)
		**out = **in
	}
	if in.OnMovieDelete != nil {
		in, out := &in.OnMovieDelete, &out.OnMovieDelete
		*out = new(bool)
		**out = **in
	}
	if in.OnMovieFileDelete != nil {
		in, out := &in.OnMovieFileDelete, &out.OnMovieFileDelete
		*out = new(bool)
		**out = **in
	}
	if in.OnMovieFileDeleteForUpgrade != nil {
		in, out := &in.OnMovieFileDeleteForUpgrade, &out.OnMovieFileDeleteForUpgrade
		*out = new(bool)
		**out = **in
	}
	if in.OnSeriesAdd != nil {
		in, out := &in.OnSeriesAdd, &out.OnSeriesAdd
		*out = new(bool)
		**out = **in
	}
	if in.OnSeriesDelete != nil {
		in, out := &in.OnSeriesDelete, &out.OnSeriesDelete
		*out = new(bool)
		**out = **in
	}
	if in.OnEpisodeFileDelete != nil {
		in, out := &in.OnEpisodeFileDelete, &out.OnEpisodeFileDelete
		*out = new(bool)
		**out = **in
	}
	if in.OnEpisodeFileDeleteForUpgrade != nil {
		in, out := &in.OnEpisodeFileDeleteForUpgrade, &out.OnEpisodeFileDeleteForUpgrade
		*out = new(bool)
		**out = **in
	}
	if in.OnReleaseImport != nil {
		in, out := &in.OnReleaseImport, &out.OnReleaseImport
		*out = new(bool)
		**out = **in
	}
	if in.OnArtistAdd != nil {
		in, out := &in.OnArtistAdd, &out.OnArtistAdd
		*out = new(bool)
		**out = **in
	}
	if in.OnArtistDelete != nil {
		in, out := &in.OnArtistDelete, &out.OnArtistDelete
		*out = new(bool)
		**out = **in
	}
	if in.OnAlbumDelete != nil {
		in, out := &in.OnAlbumDelete, &out.OnAlbumDelete
		*out = new(bool)
		**out = **in
	}
	if in.OnTrackRetag != nil {
		in, out := &in.OnTrackRetag, &out.OnTrackRetag
		*out = new(bool)
		**out = **in
	}
	if in.OnDownloadFailure != nil {
		in, out := &in.OnDownloadFailure, &out.OnDownloadFailure
		*out = new(bool)
		**out = **in
	}
	if in.OnImportFailure != nil {
		in, out := &in.OnImportFailure, &out.OnImportFailure
		*out = new(bool)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SettingsSecretRef != nil {
		in, out := &in.SettingsSecretRef, &out.SettingsSecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationSpec.
func (in *NotificationSpec) DeepCopy() *NotificationSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatus) DeepCopyInto(out *PolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatus.
func (in *PolicyStatus) DeepCopy() *PolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrApplication) DeepCopyInto(out *ProwlarrApplication) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.SyncCategories != nil {
		in, out := &in.SyncCategories, &out.SyncCategories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrApplication.
func (in *ProwlarrApplication) DeepCopy() *ProwlarrApplication {
	if in == nil {
		return nil
	}
	out := new(ProwlarrApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrConfig) DeepCopyInto(out *ProwlarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrConfig.
func (in *ProwlarrConfig) DeepCopy() *ProwlarrConfig {
	if in == nil {
		return nil
	}
	out := new(ProwlarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProwlarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrConfigList) DeepCopyInto(out *ProwlarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProwlarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrConfigList.
func (in *ProwlarrConfigList) DeepCopy() *ProwlarrConfigList {
	if in == nil {
		return nil
	}
	out := new(ProwlarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProwlarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrConfigSpec) DeepCopyInto(out *ProwlarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = make([]ProwlarrIndexer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Proxies != nil {
		in, out := &in.Proxies, &out.Proxies
		*out = make([]IndexerProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Applications != nil {
		in, out := &in.Applications, &out.Applications
		*out = make([]ProwlarrApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DownloadClients != nil {
		in, out := &in.DownloadClients, &out.DownloadClients
		*out = make([]DownloadClientSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(AuthenticationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Reconciliation != nil {
		in, out := &in.Reconciliation, &out.Reconciliation
		*out = new(ReconciliationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrConfigSpec.
func (in *ProwlarrConfigSpec) DeepCopy() *ProwlarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ProwlarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrConfigStatus) DeepCopyInto(out *ProwlarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcile != nil {
		in, out := &in.LastReconcile, &out.LastReconcile
		*out = (*in).DeepCopy()
	}
	if in.ManagedIndexers != nil {
		in, out := &in.ManagedIndexers, &out.ManagedIndexers
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ManagedProxies != nil {
		in, out := &in.ManagedProxies, &out.ManagedProxies
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ManagedApplications != nil {
		in, out := &in.ManagedApplications, &out.ManagedApplications
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(HealthStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrConfigStatus.
func (in *ProwlarrConfigStatus) DeepCopy() *ProwlarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ProwlarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrIndexer) DeepCopyInto(out *ProwlarrIndexer) {
	*out = *in
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrIndexer.
func (in *ProwlarrIndexer) DeepCopy() *ProwlarrIndexer {
	if in == nil {
		return nil
	}
	out := new(ProwlarrIndexer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrRef) DeepCopyInto(out *ProwlarrRef) {
	*out = *in
	if in.AutoRegister != nil {
		in, out := &in.AutoRegister, &out.AutoRegister
		*out = new(bool)
		**out = **in
	}
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrRef.
func (in *ProwlarrRef) DeepCopy() *ProwlarrRef {
	if in == nil {
		return nil
	}
	out := new(ProwlarrRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrRegistration) DeepCopyInto(out *ProwlarrRegistration) {
	*out = *in
	if in.ApplicationID != nil {
		in, out := &in.ApplicationID, &out.ApplicationID
		*out = new(int)
		**out = **in
	}
	if in.LastSync != nil {
		in, out := &in.LastSync, &out.LastSync
		*out = (*in).DeepCopy()
	}
	if in.SyncedIndexers != nil {
		in, out := &in.SyncedIndexers, &out.SyncedIndexers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrRegistration.
func (in *ProwlarrRegistration) DeepCopy() *ProwlarrRegistration {
	if in == nil {
		return nil
	}
	out := new(ProwlarrRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrConfig) DeepCopyInto(out *RadarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrConfig.
func (in *RadarrConfig) DeepCopy() *RadarrConfig {
	if in == nil {
		return nil
	}
	out := new(RadarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RadarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrConfigList) DeepCopyInto(out *RadarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RadarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrConfigList.
func (in *RadarrConfigList) DeepCopy() *RadarrConfigList {
	if in == nil {
		return nil
	}
	out := new(RadarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RadarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrConfigSpec) DeepCopyInto(out *RadarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Quality != nil {
		in, out := &in.Quality, &out.Quality
		*out = new(VideoQualitySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DownloadClients != nil {
		in, out := &in.DownloadClients, &out.DownloadClients
		*out = make([]DownloadClientSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RemotePathMappings != nil {
		in, out := &in.RemotePathMappings, &out.RemotePathMappings
		*out = make([]RemotePathMappingSpec, len(*in))
		copy(*out, *in)
	}
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = new(IndexersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Naming != nil {
		in, out := &in.Naming, &out.Naming
		*out = new(NamingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RootFolders != nil {
		in, out := &in.RootFolders, &out.RootFolders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImportLists != nil {
		in, out := &in.ImportLists, &out.ImportLists
		*out = make([]ImportListSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MediaManagement != nil {
		in, out := &in.MediaManagement, &out.MediaManagement
		*out = new(MediaManagementSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(AuthenticationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]NotificationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomFormats != nil {
		in, out := &in.CustomFormats, &out.CustomFormats
		*out = make([]CustomFormatSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DelayProfiles != nil {
		in, out := &in.DelayProfiles, &out.DelayProfiles
		*out = make([]DelayProfileSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reconciliation != nil {
		in, out := &in.Reconciliation, &out.Reconciliation
		*out = new(ReconciliationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrConfigSpec.
func (in *RadarrConfigSpec) DeepCopy() *RadarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RadarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrConfigStatus) DeepCopyInto(out *RadarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcile != nil {
		in, out := &in.LastReconcile, &out.LastReconcile
		*out = (*in).DeepCopy()
	}
	in.ManagedResources.DeepCopyInto(&out.ManagedResources)
	if in.ProwlarrRegistration != nil {
		in, out := &in.ProwlarrRegistration, &out.ProwlarrRegistration
		*out = new(ProwlarrRegistration)
		(*in).DeepCopyInto(*out)
	}
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(HealthStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrConfigStatus.
func (in *RadarrConfigStatus) DeepCopy() *RadarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(RadarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconciliationSpec) DeepCopyInto(out *ReconciliationSpec) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconciliationSpec.
func (in *ReconciliationSpec) DeepCopy() *ReconciliationSpec {
	if in == nil {
		return nil
	}
	out := new(ReconciliationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemotePathMappingSpec) DeepCopyInto(out *RemotePathMappingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemotePathMappingSpec.
func (in *RemotePathMappingSpec) DeepCopy() *RemotePathMappingSpec {
	if in == nil {
		return nil
	}
	out := new(RemotePathMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrConfig) DeepCopyInto(out *SonarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrConfig.
func (in *SonarrConfig) DeepCopy() *SonarrConfig {
	if in == nil {
		return nil
	}
	out := new(SonarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SonarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrConfigList) DeepCopyInto(out *SonarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SonarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrConfigList.
func (in *SonarrConfigList) DeepCopy() *SonarrConfigList {
	if in == nil {
		return nil
	}
	out := new(SonarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SonarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrConfigSpec) DeepCopyInto(out *SonarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Quality != nil {
		in, out := &in.Quality, &out.Quality
		*out = new(VideoQualitySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DownloadClients != nil {
		in, out := &in.DownloadClients, &out.DownloadClients
		*out = make([]DownloadClientSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RemotePathMappings != nil {
		in, out := &in.RemotePathMappings, &out.RemotePathMappings
		*out = make([]RemotePathMappingSpec, len(*in))
		copy(*out, *in)
	}
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = new(IndexersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Naming != nil {
		in, out := &in.Naming, &out.Naming
		*out = new(SonarrNamingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RootFolders != nil {
		in, out := &in.RootFolders, &out.RootFolders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImportLists != nil {
		in, out := &in.ImportLists, &out.ImportLists
		*out = make([]ImportListSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MediaManagement != nil {
		in, out := &in.MediaManagement, &out.MediaManagement
		*out = new(MediaManagementSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(AuthenticationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]NotificationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomFormats != nil {
		in, out := &in.CustomFormats, &out.CustomFormats
		*out = make([]CustomFormatSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DelayProfiles != nil {
		in, out := &in.DelayProfiles, &out.DelayProfiles
		*out = make([]DelayProfileSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reconciliation != nil {
		in, out := &in.Reconciliation, &out.Reconciliation
		*out = new(ReconciliationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrConfigSpec.
func (in *SonarrConfigSpec) DeepCopy() *SonarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SonarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrConfigStatus) DeepCopyInto(out *SonarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcile != nil {
		in, out := &in.LastReconcile, &out.LastReconcile
		*out = (*in).DeepCopy()
	}
	in.ManagedResources.DeepCopyInto(&out.ManagedResources)
	if in.ProwlarrRegistration != nil {
		in, out := &in.ProwlarrRegistration, &out.ProwlarrRegistration
		*out = new(ProwlarrRegistration)
		(*in).DeepCopyInto(*out)
	}
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(HealthStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrConfigStatus.
func (in *SonarrConfigStatus) DeepCopy() *SonarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SonarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrNamingSpec) DeepCopyInto(out *SonarrNamingSpec) {
	*out = *in
	in.NamingSpec.DeepCopyInto(&out.NamingSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrNamingSpec.
func (in *SonarrNamingSpec) DeepCopy() *SonarrNamingSpec {
	if in == nil {
		return nil
	}
	out := new(SonarrNamingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransmissionAltSpeedSpec) DeepCopyInto(out *TransmissionAltSpeedSpec) {
	*out = *in
	if in.TimeDays != nil {
		in, out := &in.TimeDays, &out.TimeDays
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransmissionAltSpeedSpec.
func (in *TransmissionAltSpeedSpec) DeepCopy() *TransmissionAltSpeedSpec {
	if in == nil {
		return nil
	}
	out := new(TransmissionAltSpeedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransmissionBlocklistSpec) DeepCopyInto(out *TransmissionBlocklistSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransmissionBlocklistSpec.
func (in *TransmissionBlocklistSpec) DeepCopy() *TransmissionBlocklistSpec {
	if in == nil {
		return nil
	}
	out := new(TransmissionBlocklistSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransmissionConnectionSpec) DeepCopyInto(out *TransmissionConnectionSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(CredentialsSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransmissionConnectionSpec.
func (in *TransmissionConnectionSpec) DeepCopy() *TransmissionConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(TransmissionConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransmissionDirectoriesSpec) DeepCopyInto(out *TransmissionDirectoriesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransmissionDirectoriesSpec.
func (in *TransmissionDirectoriesSpec) DeepCopy() *TransmissionDirectoriesSpec {
	if in == nil {
		return nil
	}
	out := new(TransmissionDirectoriesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransmissionPeersSpec) DeepCopyInto(out *TransmissionPeersSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransmissionPeersSpec.
func (in *TransmissionPeersSpec) DeepCopy() *TransmissionPeersSpec {
	if in == nil {
		return nil
	}
	out := new(TransmissionPeersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransmissionQueueSpec) DeepCopyInto(out *TransmissionQueueSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransmissionQueueSpec.
func (in *TransmissionQueueSpec) DeepCopy() *TransmissionQueueSpec {
	if in == nil {
		return nil
	}
	out := new(TransmissionQueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransmissionSecuritySpec) DeepCopyInto(out *TransmissionSecuritySpec) {
	*out = *in
	if in.PEXEnabled != nil {
		in, out := &in.PEXEnabled, &out.PEXEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DHTEnabled != nil {
		in, out := &in.DHTEnabled, &out.DHTEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LPDEnabled != nil {
		in, out := &in.LPDEnabled, &out.LPDEnabled
		*out = new(bool)
		**out = **in
	}
	if in.UTPEnabled != nil {
		in, out := &in.UTPEnabled, &out.UTPEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransmissionSecuritySpec.
func (in *TransmissionSecuritySpec) DeepCopy() *TransmissionSecuritySpec {
	if in == nil {
		return nil
	}
	out := new(TransmissionSecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransmissionSeedingSpec) DeepCopyInto(out *TransmissionSeedingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransmissionSeedingSpec.
func (in *TransmissionSeedingSpec) DeepCopy() *TransmissionSeedingSpec {
	if in == nil {
		return nil
	}
	out := new(TransmissionSeedingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransmissionSpec) DeepCopyInto(out *TransmissionSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Speed != nil {
		in, out := &in.Speed, &out.Speed
		*out = new(TransmissionSpeedSpec)
		**out = **in
	}
	if in.AltSpeed != nil {
		in, out := &in.AltSpeed, &out.AltSpeed
		*out = new(TransmissionAltSpeedSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Directories != nil {
		in, out := &in.Directories, &out.Directories
		*out = new(TransmissionDirectoriesSpec)
		**out = **in
	}
	if in.Seeding != nil {
		in, out := &in.Seeding, &out.Seeding
		*out = new(TransmissionSeedingSpec)
		**out = **in
	}
	if in.Queue != nil {
		in, out := &in.Queue, &out.Queue
		*out = new(TransmissionQueueSpec)
		**out = **in
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = new(TransmissionPeersSpec)
		**out = **in
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(TransmissionSecuritySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Blocklist != nil {
		in, out := &in.Blocklist, &out.Blocklist
		*out = new(TransmissionBlocklistSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransmissionSpec.
func (in *TransmissionSpec) DeepCopy() *TransmissionSpec {
	if in == nil {
		return nil
	}
	out := new(TransmissionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransmissionSpeedSpec) DeepCopyInto(out *TransmissionSpeedSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransmissionSpeedSpec.
func (in *TransmissionSpeedSpec) DeepCopy() *TransmissionSpeedSpec {
	if in == nil {
		return nil
	}
	out := new(TransmissionSpeedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoQualitySpec) DeepCopyInto(out *VideoQualitySpec) {
	*out = *in
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreferAdditional != nil {
		in, out := &in.PreferAdditional, &out.PreferAdditional
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RejectAdditional != nil {
		in, out := &in.RejectAdditional, &out.RejectAdditional
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tiers != nil {
		in, out := &in.Tiers, &out.Tiers
		*out = make([]VideoQualityTier, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UpgradeUntil != nil {
		in, out := &in.UpgradeUntil, &out.UpgradeUntil
		*out = new(VideoQualityTier)
		(*in).DeepCopyInto(*out)
	}
	if in.PreferredFormats != nil {
		in, out := &in.PreferredFormats, &out.PreferredFormats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RejectedFormats != nil {
		in, out := &in.RejectedFormats, &out.RejectedFormats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoQualitySpec.
func (in *VideoQualitySpec) DeepCopy() *VideoQualitySpec {
	if in == nil {
		return nil
	}
	out := new(VideoQualitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoQualityTier) DeepCopyInto(out *VideoQualityTier) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoQualityTier.
func (in *VideoQualityTier) DeepCopy() *VideoQualityTier {
	if in == nil {
		return nil
	}
	out := new(VideoQualityTier)
	in.DeepCopyInto(out)
	return out
}
