//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudioQualitySpec) DeepCopyInto(out *AudioQualitySpec) {
	*out = *in
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreferAdditional != nil {
		in, out := &in.PreferAdditional, &out.PreferAdditional
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tiers != nil {
		in, out := &in.Tiers, &out.Tiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreferredFormats != nil {
		in, out := &in.PreferredFormats, &out.PreferredFormats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudioQualitySpec.
func (in *AudioQualitySpec) DeepCopy() *AudioQualitySpec {
	if in == nil {
		return nil
	}
	out := new(AudioQualitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSpec) DeepCopyInto(out *ConnectionSpec) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSpec.
func (in *ConnectionSpec) DeepCopy() *ConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsSecretRef) DeepCopyInto(out *CredentialsSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsSecretRef.
func (in *CredentialsSecretRef) DeepCopy() *CredentialsSecretRef {
	if in == nil {
		return nil
	}
	out := new(CredentialsSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirectIndexer) DeepCopyInto(out *DirectIndexer) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirectIndexer.
func (in *DirectIndexer) DeepCopy() *DirectIndexer {
	if in == nil {
		return nil
	}
	out := new(DirectIndexer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadClientSpec) DeepCopyInto(out *DownloadClientSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(CredentialsSecretRef)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadClientSpec.
func (in *DownloadClientSpec) DeepCopy() *DownloadClientSpec {
	if in == nil {
		return nil
	}
	out := new(DownloadClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexerProxy) DeepCopyInto(out *IndexerProxy) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(CredentialsSecretRef)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexerProxy.
func (in *IndexerProxy) DeepCopy() *IndexerProxy {
	if in == nil {
		return nil
	}
	out := new(IndexerProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexersSpec) DeepCopyInto(out *IndexersSpec) {
	*out = *in
	if in.ProwlarrRef != nil {
		in, out := &in.ProwlarrRef, &out.ProwlarrRef
		*out = new(ProwlarrRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Direct != nil {
		in, out := &in.Direct, &out.Direct
		*out = make([]DirectIndexer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexersSpec.
func (in *IndexersSpec) DeepCopy() *IndexersSpec {
	if in == nil {
		return nil
	}
	out := new(IndexersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrConfig) DeepCopyInto(out *LidarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrConfig.
func (in *LidarrConfig) DeepCopy() *LidarrConfig {
	if in == nil {
		return nil
	}
	out := new(LidarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LidarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrConfigList) DeepCopyInto(out *LidarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LidarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrConfigList.
func (in *LidarrConfigList) DeepCopy() *LidarrConfigList {
	if in == nil {
		return nil
	}
	out := new(LidarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LidarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrConfigSpec) DeepCopyInto(out *LidarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Quality != nil {
		in, out := &in.Quality, &out.Quality
		*out = new(AudioQualitySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(MetadataProfileSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DownloadClients != nil {
		in, out := &in.DownloadClients, &out.DownloadClients
		*out = make([]DownloadClientSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = new(IndexersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Naming != nil {
		in, out := &in.Naming, &out.Naming
		*out = new(LidarrNamingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RootFolders != nil {
		in, out := &in.RootFolders, &out.RootFolders
		*out = make([]LidarrRootFolder, len(*in))
		copy(*out, *in)
	}
	if in.Reconciliation != nil {
		in, out := &in.Reconciliation, &out.Reconciliation
		*out = new(ReconciliationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrConfigSpec.
func (in *LidarrConfigSpec) DeepCopy() *LidarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(LidarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrConfigStatus) DeepCopyInto(out *LidarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcile != nil {
		in, out := &in.LastReconcile, &out.LastReconcile
		*out = (*in).DeepCopy()
	}
	in.ManagedResources.DeepCopyInto(&out.ManagedResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrConfigStatus.
func (in *LidarrConfigStatus) DeepCopy() *LidarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(LidarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrNamingSpec) DeepCopyInto(out *LidarrNamingSpec) {
	*out = *in
	in.NamingSpec.DeepCopyInto(&out.NamingSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrNamingSpec.
func (in *LidarrNamingSpec) DeepCopy() *LidarrNamingSpec {
	if in == nil {
		return nil
	}
	out := new(LidarrNamingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrRootFolder) DeepCopyInto(out *LidarrRootFolder) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrRootFolder.
func (in *LidarrRootFolder) DeepCopy() *LidarrRootFolder {
	if in == nil {
		return nil
	}
	out := new(LidarrRootFolder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResources) DeepCopyInto(out *ManagedResources) {
	*out = *in
	if in.QualityProfileID != nil {
		in, out := &in.QualityProfileID, &out.QualityProfileID
		*out = new(int)
		**out = **in
	}
	if in.CustomFormatIDs != nil {
		in, out := &in.CustomFormatIDs, &out.CustomFormatIDs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.DownloadClientIDs != nil {
		in, out := &in.DownloadClientIDs, &out.DownloadClientIDs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.IndexerIDs != nil {
		in, out := &in.IndexerIDs, &out.IndexerIDs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.RootFolderIDs != nil {
		in, out := &in.RootFolderIDs, &out.RootFolderIDs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResources.
func (in *ManagedResources) DeepCopy() *ManagedResources {
	if in == nil {
		return nil
	}
	out := new(ManagedResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataProfileSpec) DeepCopyInto(out *MetadataProfileSpec) {
	*out = *in
	if in.PrimaryTypes != nil {
		in, out := &in.PrimaryTypes, &out.PrimaryTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecondaryTypes != nil {
		in, out := &in.SecondaryTypes, &out.SecondaryTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReleaseStatuses != nil {
		in, out := &in.ReleaseStatuses, &out.ReleaseStatuses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataProfileSpec.
func (in *MetadataProfileSpec) DeepCopy() *MetadataProfileSpec {
	if in == nil {
		return nil
	}
	out := new(MetadataProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamingSpec) DeepCopyInto(out *NamingSpec) {
	*out = *in
	if in.RenameMedia != nil {
		in, out := &in.RenameMedia, &out.RenameMedia
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamingSpec.
func (in *NamingSpec) DeepCopy() *NamingSpec {
	if in == nil {
		return nil
	}
	out := new(NamingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatus) DeepCopyInto(out *PolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatus.
func (in *PolicyStatus) DeepCopy() *PolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrApplication) DeepCopyInto(out *ProwlarrApplication) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.SyncCategories != nil {
		in, out := &in.SyncCategories, &out.SyncCategories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrApplication.
func (in *ProwlarrApplication) DeepCopy() *ProwlarrApplication {
	if in == nil {
		return nil
	}
	out := new(ProwlarrApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrConfig) DeepCopyInto(out *ProwlarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrConfig.
func (in *ProwlarrConfig) DeepCopy() *ProwlarrConfig {
	if in == nil {
		return nil
	}
	out := new(ProwlarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProwlarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrConfigList) DeepCopyInto(out *ProwlarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProwlarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrConfigList.
func (in *ProwlarrConfigList) DeepCopy() *ProwlarrConfigList {
	if in == nil {
		return nil
	}
	out := new(ProwlarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProwlarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrConfigSpec) DeepCopyInto(out *ProwlarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = make([]ProwlarrIndexer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Proxies != nil {
		in, out := &in.Proxies, &out.Proxies
		*out = make([]IndexerProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Applications != nil {
		in, out := &in.Applications, &out.Applications
		*out = make([]ProwlarrApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DownloadClients != nil {
		in, out := &in.DownloadClients, &out.DownloadClients
		*out = make([]DownloadClientSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reconciliation != nil {
		in, out := &in.Reconciliation, &out.Reconciliation
		*out = new(ReconciliationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrConfigSpec.
func (in *ProwlarrConfigSpec) DeepCopy() *ProwlarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ProwlarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrConfigStatus) DeepCopyInto(out *ProwlarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcile != nil {
		in, out := &in.LastReconcile, &out.LastReconcile
		*out = (*in).DeepCopy()
	}
	if in.ManagedIndexers != nil {
		in, out := &in.ManagedIndexers, &out.ManagedIndexers
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ManagedProxies != nil {
		in, out := &in.ManagedProxies, &out.ManagedProxies
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ManagedApplications != nil {
		in, out := &in.ManagedApplications, &out.ManagedApplications
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrConfigStatus.
func (in *ProwlarrConfigStatus) DeepCopy() *ProwlarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ProwlarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrIndexer) DeepCopyInto(out *ProwlarrIndexer) {
	*out = *in
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrIndexer.
func (in *ProwlarrIndexer) DeepCopy() *ProwlarrIndexer {
	if in == nil {
		return nil
	}
	out := new(ProwlarrIndexer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrRef) DeepCopyInto(out *ProwlarrRef) {
	*out = *in
	if in.AutoRegister != nil {
		in, out := &in.AutoRegister, &out.AutoRegister
		*out = new(bool)
		**out = **in
	}
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrRef.
func (in *ProwlarrRef) DeepCopy() *ProwlarrRef {
	if in == nil {
		return nil
	}
	out := new(ProwlarrRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrConfig) DeepCopyInto(out *RadarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrConfig.
func (in *RadarrConfig) DeepCopy() *RadarrConfig {
	if in == nil {
		return nil
	}
	out := new(RadarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RadarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrConfigList) DeepCopyInto(out *RadarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RadarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrConfigList.
func (in *RadarrConfigList) DeepCopy() *RadarrConfigList {
	if in == nil {
		return nil
	}
	out := new(RadarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RadarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrConfigSpec) DeepCopyInto(out *RadarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Quality != nil {
		in, out := &in.Quality, &out.Quality
		*out = new(VideoQualitySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DownloadClients != nil {
		in, out := &in.DownloadClients, &out.DownloadClients
		*out = make([]DownloadClientSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = new(IndexersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Naming != nil {
		in, out := &in.Naming, &out.Naming
		*out = new(NamingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RootFolders != nil {
		in, out := &in.RootFolders, &out.RootFolders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Reconciliation != nil {
		in, out := &in.Reconciliation, &out.Reconciliation
		*out = new(ReconciliationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrConfigSpec.
func (in *RadarrConfigSpec) DeepCopy() *RadarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RadarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrConfigStatus) DeepCopyInto(out *RadarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcile != nil {
		in, out := &in.LastReconcile, &out.LastReconcile
		*out = (*in).DeepCopy()
	}
	in.ManagedResources.DeepCopyInto(&out.ManagedResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrConfigStatus.
func (in *RadarrConfigStatus) DeepCopy() *RadarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(RadarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconciliationSpec) DeepCopyInto(out *ReconciliationSpec) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconciliationSpec.
func (in *ReconciliationSpec) DeepCopy() *ReconciliationSpec {
	if in == nil {
		return nil
	}
	out := new(ReconciliationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrConfig) DeepCopyInto(out *SonarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrConfig.
func (in *SonarrConfig) DeepCopy() *SonarrConfig {
	if in == nil {
		return nil
	}
	out := new(SonarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SonarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrConfigList) DeepCopyInto(out *SonarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SonarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrConfigList.
func (in *SonarrConfigList) DeepCopy() *SonarrConfigList {
	if in == nil {
		return nil
	}
	out := new(SonarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SonarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrConfigSpec) DeepCopyInto(out *SonarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Quality != nil {
		in, out := &in.Quality, &out.Quality
		*out = new(VideoQualitySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DownloadClients != nil {
		in, out := &in.DownloadClients, &out.DownloadClients
		*out = make([]DownloadClientSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = new(IndexersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Naming != nil {
		in, out := &in.Naming, &out.Naming
		*out = new(SonarrNamingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RootFolders != nil {
		in, out := &in.RootFolders, &out.RootFolders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Reconciliation != nil {
		in, out := &in.Reconciliation, &out.Reconciliation
		*out = new(ReconciliationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrConfigSpec.
func (in *SonarrConfigSpec) DeepCopy() *SonarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SonarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrConfigStatus) DeepCopyInto(out *SonarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcile != nil {
		in, out := &in.LastReconcile, &out.LastReconcile
		*out = (*in).DeepCopy()
	}
	in.ManagedResources.DeepCopyInto(&out.ManagedResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrConfigStatus.
func (in *SonarrConfigStatus) DeepCopy() *SonarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SonarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrNamingSpec) DeepCopyInto(out *SonarrNamingSpec) {
	*out = *in
	in.NamingSpec.DeepCopyInto(&out.NamingSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrNamingSpec.
func (in *SonarrNamingSpec) DeepCopy() *SonarrNamingSpec {
	if in == nil {
		return nil
	}
	out := new(SonarrNamingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoQualitySpec) DeepCopyInto(out *VideoQualitySpec) {
	*out = *in
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreferAdditional != nil {
		in, out := &in.PreferAdditional, &out.PreferAdditional
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RejectAdditional != nil {
		in, out := &in.RejectAdditional, &out.RejectAdditional
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tiers != nil {
		in, out := &in.Tiers, &out.Tiers
		*out = make([]VideoQualityTier, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UpgradeUntil != nil {
		in, out := &in.UpgradeUntil, &out.UpgradeUntil
		*out = new(VideoQualityTier)
		(*in).DeepCopyInto(*out)
	}
	if in.PreferredFormats != nil {
		in, out := &in.PreferredFormats, &out.PreferredFormats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RejectedFormats != nil {
		in, out := &in.RejectedFormats, &out.RejectedFormats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoQualitySpec.
func (in *VideoQualitySpec) DeepCopy() *VideoQualitySpec {
	if in == nil {
		return nil
	}
	out := new(VideoQualitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoQualityTier) DeepCopyInto(out *VideoQualityTier) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoQualityTier.
func (in *VideoQualityTier) DeepCopy() *VideoQualityTier {
	if in == nil {
		return nil
	}
	out := new(VideoQualityTier)
	in.DeepCopyInto(out)
	return out
}
